server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${USERNAME}
    password: ${PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
appDescription: "Pragma Powerup"
appVersion: "1.0.0"

feign:
  twilio: ${TWILIO_URL}
  client: ${CLIENT_URL}
